package rtmp

const (
	AMF_NUMBER = iota
	AMF_BOOLEAN
	AMF_STRING
	AMF_OBJECT
	AMF_MOVIECLIP /* RESERVED, NOT USED */
	AMF_NULL
	AMF_UNDEFINED
	AMF_REFERENCE
	AMF_ECMA_ARRAY
	AMF_OBJECT_END
	AMF_STRICT_ARRAY
	AMF_DATE
	AMF_LONG_STRING
	AMF_UNSUPPORTED
	AMF_RECORDSET /* RESERVED, NOT USED */
	AMF_XML_DOC
	AMF_TYPED_OBJECT
	AMF_AVMPLUS /* SWITCH TO AMF3 */
	AMF_INVALID = 0xFF
)

type AMF map[string]interface{}
